# Generated by Django 5.2.9 on 2025-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('familiya', models.TextField(blank=True, null=True)),
                ('telefon_nomer', models.CharField(max_length=225, unique=True)),
                ('email', models.TextField(unique=True)),
                ('biografiya', models.CharField(blank=True, null=True)),
                ('yosh', models.TextField(default=0)),
                ('kurs', models.CharField(choices=[('1-course', '1-course'), ('2-course', '2-course'), ('3-course', '3-course'), ('4-course', '4-course')], max_length=15)),
                ('rasm', models.ImageField(upload_to='')),
                ('tugallaganmi', models.BooleanField(default=False)),
                ('tugilgan_kun', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
